export const data = [
    { id: 63, name: 'Phun xăm chân mày', img: '' },
    { id: 14, name: 'Chăm sóc da', img: '' },
    { id: 21, name: 'Trắng da vùng mặt', img: '' },
    { id: 14, name: 'Chăm sóc da', img: '' },
    { id: 119, name: 'Điều trị nha khoa', img: '' },
    { id: 111, name: 'Trị sẹo', img: '' },
    { id: 34, name: 'Uốn tóc', img: '' },
    { id: 18, name: 'Tẩy lông', img: '' },
    { id: 101, name: 'Giảm béo bằng công nghệ', img: '' },
    { id: 46, name: 'Sơn móng', img: '' },
    { id: 12, name: 'Gội đầu thư giãn', img: '' },
    { id: 14, name: 'Căng da mặt', img: '' },
    { id: 63, name: 'Phun xăm chân mày', img: '' },
    { id: 14, name: 'Chăm sóc da', img: '' },
    { id: 63, name: 'Phun xăm chân mày', img: '' },
    { id: 14, name: 'Chăm sóc da', img: '' },
]
