import { IOrganization } from 'interface';

export const orgInit: IOrganization = {
    id: 0,
    name: '',
    subdomain: '',
    latitude: 0,
    longitude: 0,
    address: '',
    min_price: 0,
    max_price: 0,
    image: '',
    is_momo_ecommerce_enable: false,
    created_at: '',
    updated_at: '',
    province_code: 0,
    district_code: 0,
    ward_code: 0,
    full_address: '',
    image_url: "",
    branches: [],
    opening_time: [],
    description: '',
    favorites_count: 0,
    is_favorite: false,
    favorites: [],
    distance: 0,
    tags: [],
    telephone: [],
}